// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// empty message
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// message that only contains a value of string
type StringMsg struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMsg) Reset()         { *m = StringMsg{} }
func (m *StringMsg) String() string { return proto.CompactTextString(m) }
func (*StringMsg) ProtoMessage()    {}
func (*StringMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *StringMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMsg.Unmarshal(m, b)
}
func (m *StringMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMsg.Marshal(b, m, deterministic)
}
func (m *StringMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMsg.Merge(m, src)
}
func (m *StringMsg) XXX_Size() int {
	return xxx_messageInfo_StringMsg.Size(m)
}
func (m *StringMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMsg.DiscardUnknown(m)
}

var xxx_messageInfo_StringMsg proto.InternalMessageInfo

func (m *StringMsg) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// message that only contains a value of string
type String2Msg struct {
	Param1               string   `protobuf:"bytes,1,opt,name=param1,proto3" json:"param1,omitempty"`
	Param2               string   `protobuf:"bytes,2,opt,name=param2,proto3" json:"param2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String2Msg) Reset()         { *m = String2Msg{} }
func (m *String2Msg) String() string { return proto.CompactTextString(m) }
func (*String2Msg) ProtoMessage()    {}
func (*String2Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *String2Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String2Msg.Unmarshal(m, b)
}
func (m *String2Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String2Msg.Marshal(b, m, deterministic)
}
func (m *String2Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String2Msg.Merge(m, src)
}
func (m *String2Msg) XXX_Size() int {
	return xxx_messageInfo_String2Msg.Size(m)
}
func (m *String2Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_String2Msg.DiscardUnknown(m)
}

var xxx_messageInfo_String2Msg proto.InternalMessageInfo

func (m *String2Msg) GetParam1() string {
	if m != nil {
		return m.Param1
	}
	return ""
}

func (m *String2Msg) GetParam2() string {
	if m != nil {
		return m.Param2
	}
	return ""
}

// message that only contains a value of int32
type Int32Msg struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32Msg) Reset()         { *m = Int32Msg{} }
func (m *Int32Msg) String() string { return proto.CompactTextString(m) }
func (*Int32Msg) ProtoMessage()    {}
func (*Int32Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *Int32Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32Msg.Unmarshal(m, b)
}
func (m *Int32Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32Msg.Marshal(b, m, deterministic)
}
func (m *Int32Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32Msg.Merge(m, src)
}
func (m *Int32Msg) XXX_Size() int {
	return xxx_messageInfo_Int32Msg.Size(m)
}
func (m *Int32Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Int32Msg proto.InternalMessageInfo

func (m *Int32Msg) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

// message that only contains a value of int64
type Int64Msg struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64Msg) Reset()         { *m = Int64Msg{} }
func (m *Int64Msg) String() string { return proto.CompactTextString(m) }
func (*Int64Msg) ProtoMessage()    {}
func (*Int64Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *Int64Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64Msg.Unmarshal(m, b)
}
func (m *Int64Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64Msg.Marshal(b, m, deterministic)
}
func (m *Int64Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64Msg.Merge(m, src)
}
func (m *Int64Msg) XXX_Size() int {
	return xxx_messageInfo_Int64Msg.Size(m)
}
func (m *Int64Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Int64Msg proto.InternalMessageInfo

func (m *Int64Msg) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// Node message
type NodeMsg struct {
	ID                   int32            `protobuf:"varint,1,opt,name=iD,proto3" json:"iD,omitempty"`
	NodeID               string           `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	PubKey               string           `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Owner                string           `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	ProfitAcc            string           `protobuf:"bytes,5,opt,name=profitAcc,proto3" json:"profitAcc,omitempty"`
	PoolID               string           `protobuf:"bytes,6,opt,name=poolID,proto3" json:"poolID,omitempty"`
	PoolOwner            string           `protobuf:"bytes,7,opt,name=poolOwner,proto3" json:"poolOwner,omitempty"`
	Quota                int64            `protobuf:"varint,8,opt,name=quota,proto3" json:"quota,omitempty"`
	Addrs                []string         `protobuf:"bytes,9,rep,name=addrs,proto3" json:"addrs,omitempty"`
	CPU                  int32            `protobuf:"varint,10,opt,name=cPU,proto3" json:"cPU,omitempty"`
	Memory               int32            `protobuf:"varint,11,opt,name=memory,proto3" json:"memory,omitempty"`
	Bandwidth            int32            `protobuf:"varint,12,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	MaxDataSpace         int64            `protobuf:"varint,13,opt,name=maxDataSpace,proto3" json:"maxDataSpace,omitempty"`
	AssignedSpace        int64            `protobuf:"varint,14,opt,name=assignedSpace,proto3" json:"assignedSpace,omitempty"`
	ProductiveSpace      int64            `protobuf:"varint,15,opt,name=productiveSpace,proto3" json:"productiveSpace,omitempty"`
	UsedSpace            int64            `protobuf:"varint,16,opt,name=usedSpace,proto3" json:"usedSpace,omitempty"`
	Weight               float64          `protobuf:"fixed64,17,opt,name=weight,proto3" json:"weight,omitempty"`
	Valid                int32            `protobuf:"varint,18,opt,name=valid,proto3" json:"valid,omitempty"`
	Relay                int32            `protobuf:"varint,19,opt,name=relay,proto3" json:"relay,omitempty"`
	Status               int32            `protobuf:"varint,20,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp            int64            `protobuf:"varint,21,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version              int32            `protobuf:"varint,22,opt,name=version,proto3" json:"version,omitempty"`
	Rebuilding           int32            `protobuf:"varint,23,opt,name=rebuilding,proto3" json:"rebuilding,omitempty"`
	RealSpace            int64            `protobuf:"varint,24,opt,name=realSpace,proto3" json:"realSpace,omitempty"`
	Tx                   int64            `protobuf:"varint,25,opt,name=tx,proto3" json:"tx,omitempty"`
	Rx                   int64            `protobuf:"varint,26,opt,name=rx,proto3" json:"rx,omitempty"`
	Ext                  string           `protobuf:"bytes,27,opt,name=ext,proto3" json:"ext,omitempty"`
	Uspaces              map[string]int64 `protobuf:"bytes,28,rep,name=uspaces,proto3" json:"uspaces,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	ManualWeight         int32            `protobuf:"varint,29,opt,name=manualWeight,proto3" json:"manualWeight,omitempty"`
	Unreadable           bool             `protobuf:"varint,30,opt,name=unreadable,proto3" json:"unreadable,omitempty"`
	Hash                 string           `protobuf:"bytes,31,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NodeMsg) Reset()         { *m = NodeMsg{} }
func (m *NodeMsg) String() string { return proto.CompactTextString(m) }
func (*NodeMsg) ProtoMessage()    {}
func (*NodeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{5}
}

func (m *NodeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeMsg.Unmarshal(m, b)
}
func (m *NodeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeMsg.Marshal(b, m, deterministic)
}
func (m *NodeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeMsg.Merge(m, src)
}
func (m *NodeMsg) XXX_Size() int {
	return xxx_messageInfo_NodeMsg.Size(m)
}
func (m *NodeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_NodeMsg proto.InternalMessageInfo

func (m *NodeMsg) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *NodeMsg) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *NodeMsg) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *NodeMsg) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *NodeMsg) GetProfitAcc() string {
	if m != nil {
		return m.ProfitAcc
	}
	return ""
}

func (m *NodeMsg) GetPoolID() string {
	if m != nil {
		return m.PoolID
	}
	return ""
}

func (m *NodeMsg) GetPoolOwner() string {
	if m != nil {
		return m.PoolOwner
	}
	return ""
}

func (m *NodeMsg) GetQuota() int64 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *NodeMsg) GetAddrs() []string {
	if m != nil {
		return m.Addrs
	}
	return nil
}

func (m *NodeMsg) GetCPU() int32 {
	if m != nil {
		return m.CPU
	}
	return 0
}

func (m *NodeMsg) GetMemory() int32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *NodeMsg) GetBandwidth() int32 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

func (m *NodeMsg) GetMaxDataSpace() int64 {
	if m != nil {
		return m.MaxDataSpace
	}
	return 0
}

func (m *NodeMsg) GetAssignedSpace() int64 {
	if m != nil {
		return m.AssignedSpace
	}
	return 0
}

func (m *NodeMsg) GetProductiveSpace() int64 {
	if m != nil {
		return m.ProductiveSpace
	}
	return 0
}

func (m *NodeMsg) GetUsedSpace() int64 {
	if m != nil {
		return m.UsedSpace
	}
	return 0
}

func (m *NodeMsg) GetWeight() float64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *NodeMsg) GetValid() int32 {
	if m != nil {
		return m.Valid
	}
	return 0
}

func (m *NodeMsg) GetRelay() int32 {
	if m != nil {
		return m.Relay
	}
	return 0
}

func (m *NodeMsg) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *NodeMsg) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *NodeMsg) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *NodeMsg) GetRebuilding() int32 {
	if m != nil {
		return m.Rebuilding
	}
	return 0
}

func (m *NodeMsg) GetRealSpace() int64 {
	if m != nil {
		return m.RealSpace
	}
	return 0
}

func (m *NodeMsg) GetTx() int64 {
	if m != nil {
		return m.Tx
	}
	return 0
}

func (m *NodeMsg) GetRx() int64 {
	if m != nil {
		return m.Rx
	}
	return 0
}

func (m *NodeMsg) GetExt() string {
	if m != nil {
		return m.Ext
	}
	return ""
}

func (m *NodeMsg) GetUspaces() map[string]int64 {
	if m != nil {
		return m.Uspaces
	}
	return nil
}

func (m *NodeMsg) GetManualWeight() int32 {
	if m != nil {
		return m.ManualWeight
	}
	return 0
}

func (m *NodeMsg) GetUnreadable() bool {
	if m != nil {
		return m.Unreadable
	}
	return false
}

func (m *NodeMsg) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

// SuperNode message
type SuperNodeMsg struct {
	ID                   int32    `protobuf:"varint,1,opt,name=iD,proto3" json:"iD,omitempty"`
	NodeID               string   `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	PubKey               string   `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	PrivKey              string   `protobuf:"bytes,4,opt,name=privKey,proto3" json:"privKey,omitempty"`
	Addrs                []string `protobuf:"bytes,5,rep,name=addrs,proto3" json:"addrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuperNodeMsg) Reset()         { *m = SuperNodeMsg{} }
func (m *SuperNodeMsg) String() string { return proto.CompactTextString(m) }
func (*SuperNodeMsg) ProtoMessage()    {}
func (*SuperNodeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{6}
}

func (m *SuperNodeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuperNodeMsg.Unmarshal(m, b)
}
func (m *SuperNodeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuperNodeMsg.Marshal(b, m, deterministic)
}
func (m *SuperNodeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuperNodeMsg.Merge(m, src)
}
func (m *SuperNodeMsg) XXX_Size() int {
	return xxx_messageInfo_SuperNodeMsg.Size(m)
}
func (m *SuperNodeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SuperNodeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SuperNodeMsg proto.InternalMessageInfo

func (m *SuperNodeMsg) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *SuperNodeMsg) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *SuperNodeMsg) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *SuperNodeMsg) GetPrivKey() string {
	if m != nil {
		return m.PrivKey
	}
	return ""
}

func (m *SuperNodeMsg) GetAddrs() []string {
	if m != nil {
		return m.Addrs
	}
	return nil
}

// NodeStat message
type NodeStatMsg struct {
	ActiveMiners         int64    `protobuf:"varint,1,opt,name=activeMiners,proto3" json:"activeMiners,omitempty"`
	TotalMiners          int64    `protobuf:"varint,2,opt,name=totalMiners,proto3" json:"totalMiners,omitempty"`
	MaxTotal             int64    `protobuf:"varint,3,opt,name=maxTotal,proto3" json:"maxTotal,omitempty"`
	AssignedTotal        int64    `protobuf:"varint,4,opt,name=assignedTotal,proto3" json:"assignedTotal,omitempty"`
	ProductiveTotal      int64    `protobuf:"varint,5,opt,name=productiveTotal,proto3" json:"productiveTotal,omitempty"`
	UsedTotal            int64    `protobuf:"varint,6,opt,name=usedTotal,proto3" json:"usedTotal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeStatMsg) Reset()         { *m = NodeStatMsg{} }
func (m *NodeStatMsg) String() string { return proto.CompactTextString(m) }
func (*NodeStatMsg) ProtoMessage()    {}
func (*NodeStatMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{7}
}

func (m *NodeStatMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeStatMsg.Unmarshal(m, b)
}
func (m *NodeStatMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeStatMsg.Marshal(b, m, deterministic)
}
func (m *NodeStatMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStatMsg.Merge(m, src)
}
func (m *NodeStatMsg) XXX_Size() int {
	return xxx_messageInfo_NodeStatMsg.Size(m)
}
func (m *NodeStatMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStatMsg.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStatMsg proto.InternalMessageInfo

func (m *NodeStatMsg) GetActiveMiners() int64 {
	if m != nil {
		return m.ActiveMiners
	}
	return 0
}

func (m *NodeStatMsg) GetTotalMiners() int64 {
	if m != nil {
		return m.TotalMiners
	}
	return 0
}

func (m *NodeStatMsg) GetMaxTotal() int64 {
	if m != nil {
		return m.MaxTotal
	}
	return 0
}

func (m *NodeStatMsg) GetAssignedTotal() int64 {
	if m != nil {
		return m.AssignedTotal
	}
	return 0
}

func (m *NodeStatMsg) GetProductiveTotal() int64 {
	if m != nil {
		return m.ProductiveTotal
	}
	return 0
}

func (m *NodeStatMsg) GetUsedTotal() int64 {
	if m != nil {
		return m.UsedTotal
	}
	return 0
}

// SpotCheckTask message
type SpotCheckTaskMsg struct {
	ID                   int32    `protobuf:"varint,1,opt,name=iD,proto3" json:"iD,omitempty"`
	NodeID               string   `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Addr                 string   `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	VNI                  string   `protobuf:"bytes,4,opt,name=vNI,proto3" json:"vNI,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpotCheckTaskMsg) Reset()         { *m = SpotCheckTaskMsg{} }
func (m *SpotCheckTaskMsg) String() string { return proto.CompactTextString(m) }
func (*SpotCheckTaskMsg) ProtoMessage()    {}
func (*SpotCheckTaskMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{8}
}

func (m *SpotCheckTaskMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotCheckTaskMsg.Unmarshal(m, b)
}
func (m *SpotCheckTaskMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotCheckTaskMsg.Marshal(b, m, deterministic)
}
func (m *SpotCheckTaskMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotCheckTaskMsg.Merge(m, src)
}
func (m *SpotCheckTaskMsg) XXX_Size() int {
	return xxx_messageInfo_SpotCheckTaskMsg.Size(m)
}
func (m *SpotCheckTaskMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotCheckTaskMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SpotCheckTaskMsg proto.InternalMessageInfo

func (m *SpotCheckTaskMsg) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *SpotCheckTaskMsg) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *SpotCheckTaskMsg) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *SpotCheckTaskMsg) GetVNI() string {
	if m != nil {
		return m.VNI
	}
	return ""
}

// SpotCheckList message
type SpotCheckListMsg struct {
	TaskID               string              `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	TaskList             []*SpotCheckTaskMsg `protobuf:"bytes,2,rep,name=taskList,proto3" json:"taskList,omitempty"`
	Timestamp            int64               `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SpotCheckListMsg) Reset()         { *m = SpotCheckListMsg{} }
func (m *SpotCheckListMsg) String() string { return proto.CompactTextString(m) }
func (*SpotCheckListMsg) ProtoMessage()    {}
func (*SpotCheckListMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{9}
}

func (m *SpotCheckListMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotCheckListMsg.Unmarshal(m, b)
}
func (m *SpotCheckListMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotCheckListMsg.Marshal(b, m, deterministic)
}
func (m *SpotCheckListMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotCheckListMsg.Merge(m, src)
}
func (m *SpotCheckListMsg) XXX_Size() int {
	return xxx_messageInfo_SpotCheckListMsg.Size(m)
}
func (m *SpotCheckListMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotCheckListMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SpotCheckListMsg proto.InternalMessageInfo

func (m *SpotCheckListMsg) GetTaskID() string {
	if m != nil {
		return m.TaskID
	}
	return ""
}

func (m *SpotCheckListMsg) GetTaskList() []*SpotCheckTaskMsg {
	if m != nil {
		return m.TaskList
	}
	return nil
}

func (m *SpotCheckListMsg) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// response message of GetSpotCheckList function
type GetSpotCheckListResp struct {
	SpotCheckLists       []*SpotCheckListMsg `protobuf:"bytes,1,rep,name=spotCheckLists,proto3" json:"spotCheckLists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetSpotCheckListResp) Reset()         { *m = GetSpotCheckListResp{} }
func (m *GetSpotCheckListResp) String() string { return proto.CompactTextString(m) }
func (*GetSpotCheckListResp) ProtoMessage()    {}
func (*GetSpotCheckListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{10}
}

func (m *GetSpotCheckListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpotCheckListResp.Unmarshal(m, b)
}
func (m *GetSpotCheckListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpotCheckListResp.Marshal(b, m, deterministic)
}
func (m *GetSpotCheckListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpotCheckListResp.Merge(m, src)
}
func (m *GetSpotCheckListResp) XXX_Size() int {
	return xxx_messageInfo_GetSpotCheckListResp.Size(m)
}
func (m *GetSpotCheckListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpotCheckListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpotCheckListResp proto.InternalMessageInfo

func (m *GetSpotCheckListResp) GetSpotCheckLists() []*SpotCheckListMsg {
	if m != nil {
		return m.SpotCheckLists
	}
	return nil
}

// response message with multiple nodes
type NodesResp struct {
	Nodes                []*NodeMsg `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NodesResp) Reset()         { *m = NodesResp{} }
func (m *NodesResp) String() string { return proto.CompactTextString(m) }
func (*NodesResp) ProtoMessage()    {}
func (*NodesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{11}
}

func (m *NodesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodesResp.Unmarshal(m, b)
}
func (m *NodesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodesResp.Marshal(b, m, deterministic)
}
func (m *NodesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodesResp.Merge(m, src)
}
func (m *NodesResp) XXX_Size() int {
	return xxx_messageInfo_NodesResp.Size(m)
}
func (m *NodesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NodesResp.DiscardUnknown(m)
}

var xxx_messageInfo_NodesResp proto.InternalMessageInfo

func (m *NodesResp) GetNodes() []*NodeMsg {
	if m != nil {
		return m.Nodes
	}
	return nil
}

// response message with multiple supernodes
type SuperNodesResp struct {
	SuperNodes           []*SuperNodeMsg `protobuf:"bytes,1,rep,name=superNodes,proto3" json:"superNodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SuperNodesResp) Reset()         { *m = SuperNodesResp{} }
func (m *SuperNodesResp) String() string { return proto.CompactTextString(m) }
func (*SuperNodesResp) ProtoMessage()    {}
func (*SuperNodesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{12}
}

func (m *SuperNodesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuperNodesResp.Unmarshal(m, b)
}
func (m *SuperNodesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuperNodesResp.Marshal(b, m, deterministic)
}
func (m *SuperNodesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuperNodesResp.Merge(m, src)
}
func (m *SuperNodesResp) XXX_Size() int {
	return xxx_messageInfo_SuperNodesResp.Size(m)
}
func (m *SuperNodesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SuperNodesResp.DiscardUnknown(m)
}

var xxx_messageInfo_SuperNodesResp proto.InternalMessageInfo

func (m *SuperNodesResp) GetSuperNodes() []*SuperNodeMsg {
	if m != nil {
		return m.SuperNodes
	}
	return nil
}

// request message of IncrUsedSpace function
type IncrUsedSpaceReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Incr                 int64    `protobuf:"varint,2,opt,name=incr,proto3" json:"incr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncrUsedSpaceReq) Reset()         { *m = IncrUsedSpaceReq{} }
func (m *IncrUsedSpaceReq) String() string { return proto.CompactTextString(m) }
func (*IncrUsedSpaceReq) ProtoMessage()    {}
func (*IncrUsedSpaceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{13}
}

func (m *IncrUsedSpaceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrUsedSpaceReq.Unmarshal(m, b)
}
func (m *IncrUsedSpaceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrUsedSpaceReq.Marshal(b, m, deterministic)
}
func (m *IncrUsedSpaceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrUsedSpaceReq.Merge(m, src)
}
func (m *IncrUsedSpaceReq) XXX_Size() int {
	return xxx_messageInfo_IncrUsedSpaceReq.Size(m)
}
func (m *IncrUsedSpaceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrUsedSpaceReq.DiscardUnknown(m)
}

var xxx_messageInfo_IncrUsedSpaceReq proto.InternalMessageInfo

func (m *IncrUsedSpaceReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *IncrUsedSpaceReq) GetIncr() int64 {
	if m != nil {
		return m.Incr
	}
	return 0
}

// request message of AllocNodes function
type AllocNodesReq struct {
	ShardCount           int32    `protobuf:"varint,1,opt,name=shardCount,proto3" json:"shardCount,omitempty"`
	ErrIDs               []int32  `protobuf:"varint,2,rep,packed,name=errIDs,proto3" json:"errIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllocNodesReq) Reset()         { *m = AllocNodesReq{} }
func (m *AllocNodesReq) String() string { return proto.CompactTextString(m) }
func (*AllocNodesReq) ProtoMessage()    {}
func (*AllocNodesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{14}
}

func (m *AllocNodesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllocNodesReq.Unmarshal(m, b)
}
func (m *AllocNodesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllocNodesReq.Marshal(b, m, deterministic)
}
func (m *AllocNodesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllocNodesReq.Merge(m, src)
}
func (m *AllocNodesReq) XXX_Size() int {
	return xxx_messageInfo_AllocNodesReq.Size(m)
}
func (m *AllocNodesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AllocNodesReq.DiscardUnknown(m)
}

var xxx_messageInfo_AllocNodesReq proto.InternalMessageInfo

func (m *AllocNodesReq) GetShardCount() int32 {
	if m != nil {
		return m.ShardCount
	}
	return 0
}

func (m *AllocNodesReq) GetErrIDs() []int32 {
	if m != nil {
		return m.ErrIDs
	}
	return nil
}

// request message of GetNodes function
type GetNodesReq struct {
	NodeIDs              []int32  `protobuf:"varint,1,rep,packed,name=nodeIDs,proto3" json:"nodeIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodesReq) Reset()         { *m = GetNodesReq{} }
func (m *GetNodesReq) String() string { return proto.CompactTextString(m) }
func (*GetNodesReq) ProtoMessage()    {}
func (*GetNodesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{15}
}

func (m *GetNodesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodesReq.Unmarshal(m, b)
}
func (m *GetNodesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodesReq.Marshal(b, m, deterministic)
}
func (m *GetNodesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodesReq.Merge(m, src)
}
func (m *GetNodesReq) XXX_Size() int {
	return xxx_messageInfo_GetNodesReq.Size(m)
}
func (m *GetNodesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodesReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodesReq proto.InternalMessageInfo

func (m *GetNodesReq) GetNodeIDs() []int32 {
	if m != nil {
		return m.NodeIDs
	}
	return nil
}

// request message of AddDNI function
type DNIReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Shard                []byte   `protobuf:"bytes,2,opt,name=shard,proto3" json:"shard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DNIReq) Reset()         { *m = DNIReq{} }
func (m *DNIReq) String() string { return proto.CompactTextString(m) }
func (*DNIReq) ProtoMessage()    {}
func (*DNIReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{16}
}

func (m *DNIReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DNIReq.Unmarshal(m, b)
}
func (m *DNIReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DNIReq.Marshal(b, m, deterministic)
}
func (m *DNIReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DNIReq.Merge(m, src)
}
func (m *DNIReq) XXX_Size() int {
	return xxx_messageInfo_DNIReq.Size(m)
}
func (m *DNIReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DNIReq.DiscardUnknown(m)
}

var xxx_messageInfo_DNIReq proto.InternalMessageInfo

func (m *DNIReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DNIReq) GetShard() []byte {
	if m != nil {
		return m.Shard
	}
	return nil
}

// request message of UpdateTaskStatus function
type UpdateTaskStatusReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InvalidNodeList      []int32  `protobuf:"varint,2,rep,packed,name=invalidNodeList,proto3" json:"invalidNodeList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskStatusReq) Reset()         { *m = UpdateTaskStatusReq{} }
func (m *UpdateTaskStatusReq) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskStatusReq) ProtoMessage()    {}
func (*UpdateTaskStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{17}
}

func (m *UpdateTaskStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskStatusReq.Unmarshal(m, b)
}
func (m *UpdateTaskStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskStatusReq.Marshal(b, m, deterministic)
}
func (m *UpdateTaskStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskStatusReq.Merge(m, src)
}
func (m *UpdateTaskStatusReq) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskStatusReq.Size(m)
}
func (m *UpdateTaskStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskStatusReq proto.InternalMessageInfo

func (m *UpdateTaskStatusReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateTaskStatusReq) GetInvalidNodeList() []int32 {
	if m != nil {
		return m.InvalidNodeList
	}
	return nil
}

// ShardCount message
type ShardCountMsg struct {
	ID                   int32    `protobuf:"varint,1,opt,name=iD,proto3" json:"iD,omitempty"`
	Cnt                  int64    `protobuf:"varint,2,opt,name=cnt,proto3" json:"cnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardCountMsg) Reset()         { *m = ShardCountMsg{} }
func (m *ShardCountMsg) String() string { return proto.CompactTextString(m) }
func (*ShardCountMsg) ProtoMessage()    {}
func (*ShardCountMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{18}
}

func (m *ShardCountMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardCountMsg.Unmarshal(m, b)
}
func (m *ShardCountMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardCountMsg.Marshal(b, m, deterministic)
}
func (m *ShardCountMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardCountMsg.Merge(m, src)
}
func (m *ShardCountMsg) XXX_Size() int {
	return xxx_messageInfo_ShardCountMsg.Size(m)
}
func (m *ShardCountMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardCountMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ShardCountMsg proto.InternalMessageInfo

func (m *ShardCountMsg) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ShardCountMsg) GetCnt() int64 {
	if m != nil {
		return m.Cnt
	}
	return 0
}

// request message of GetInvalidNodes function
type GetInvalidNodesResp struct {
	ShardCounts          []*ShardCountMsg `protobuf:"bytes,1,rep,name=shardCounts,proto3" json:"shardCounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetInvalidNodesResp) Reset()         { *m = GetInvalidNodesResp{} }
func (m *GetInvalidNodesResp) String() string { return proto.CompactTextString(m) }
func (*GetInvalidNodesResp) ProtoMessage()    {}
func (*GetInvalidNodesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{19}
}

func (m *GetInvalidNodesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInvalidNodesResp.Unmarshal(m, b)
}
func (m *GetInvalidNodesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInvalidNodesResp.Marshal(b, m, deterministic)
}
func (m *GetInvalidNodesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInvalidNodesResp.Merge(m, src)
}
func (m *GetInvalidNodesResp) XXX_Size() int {
	return xxx_messageInfo_GetInvalidNodesResp.Size(m)
}
func (m *GetInvalidNodesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInvalidNodesResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetInvalidNodesResp proto.InternalMessageInfo

func (m *GetInvalidNodesResp) GetShardCounts() []*ShardCountMsg {
	if m != nil {
		return m.ShardCounts
	}
	return nil
}

// request message of GetInvalidNodes function
type GetRebuildItemReq struct {
	MinerID              int32    `protobuf:"varint,1,opt,name=minerID,proto3" json:"minerID,omitempty"`
	Index                int64    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRebuildItemReq) Reset()         { *m = GetRebuildItemReq{} }
func (m *GetRebuildItemReq) String() string { return proto.CompactTextString(m) }
func (*GetRebuildItemReq) ProtoMessage()    {}
func (*GetRebuildItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{20}
}

func (m *GetRebuildItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRebuildItemReq.Unmarshal(m, b)
}
func (m *GetRebuildItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRebuildItemReq.Marshal(b, m, deterministic)
}
func (m *GetRebuildItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRebuildItemReq.Merge(m, src)
}
func (m *GetRebuildItemReq) XXX_Size() int {
	return xxx_messageInfo_GetRebuildItemReq.Size(m)
}
func (m *GetRebuildItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRebuildItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetRebuildItemReq proto.InternalMessageInfo

func (m *GetRebuildItemReq) GetMinerID() int32 {
	if m != nil {
		return m.MinerID
	}
	return 0
}

func (m *GetRebuildItemReq) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *GetRebuildItemReq) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

// response message of GetInvalidNodes function
type GetRebuildItemResp struct {
	Node                 *NodeMsg `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Shards               [][]byte `protobuf:"bytes,2,rep,name=shards,proto3" json:"shards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRebuildItemResp) Reset()         { *m = GetRebuildItemResp{} }
func (m *GetRebuildItemResp) String() string { return proto.CompactTextString(m) }
func (*GetRebuildItemResp) ProtoMessage()    {}
func (*GetRebuildItemResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{21}
}

func (m *GetRebuildItemResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRebuildItemResp.Unmarshal(m, b)
}
func (m *GetRebuildItemResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRebuildItemResp.Marshal(b, m, deterministic)
}
func (m *GetRebuildItemResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRebuildItemResp.Merge(m, src)
}
func (m *GetRebuildItemResp) XXX_Size() int {
	return xxx_messageInfo_GetRebuildItemResp.Size(m)
}
func (m *GetRebuildItemResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRebuildItemResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetRebuildItemResp proto.InternalMessageInfo

func (m *GetRebuildItemResp) GetNode() *NodeMsg {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *GetRebuildItemResp) GetShards() [][]byte {
	if m != nil {
		return m.Shards
	}
	return nil
}

type DownloadShardRequest struct {
	VHF                  []byte   `protobuf:"bytes,1,opt,name=VHF,proto3" json:"VHF,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadShardRequest) Reset()         { *m = DownloadShardRequest{} }
func (m *DownloadShardRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadShardRequest) ProtoMessage()    {}
func (*DownloadShardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{22}
}

func (m *DownloadShardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadShardRequest.Unmarshal(m, b)
}
func (m *DownloadShardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadShardRequest.Marshal(b, m, deterministic)
}
func (m *DownloadShardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadShardRequest.Merge(m, src)
}
func (m *DownloadShardRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadShardRequest.Size(m)
}
func (m *DownloadShardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadShardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadShardRequest proto.InternalMessageInfo

func (m *DownloadShardRequest) GetVHF() []byte {
	if m != nil {
		return m.VHF
	}
	return nil
}

type DownloadShardResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadShardResponse) Reset()         { *m = DownloadShardResponse{} }
func (m *DownloadShardResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadShardResponse) ProtoMessage()    {}
func (*DownloadShardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{23}
}

func (m *DownloadShardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadShardResponse.Unmarshal(m, b)
}
func (m *DownloadShardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadShardResponse.Marshal(b, m, deterministic)
}
func (m *DownloadShardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadShardResponse.Merge(m, src)
}
func (m *DownloadShardResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadShardResponse.Size(m)
}
func (m *DownloadShardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadShardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadShardResponse proto.InternalMessageInfo

func (m *DownloadShardResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SignMessage struct {
	AccountName          string   `protobuf:"bytes,1,opt,name=accountName,proto3" json:"accountName,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Signature            string   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignMessage) Reset()         { *m = SignMessage{} }
func (m *SignMessage) String() string { return proto.CompactTextString(m) }
func (*SignMessage) ProtoMessage()    {}
func (*SignMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{24}
}

func (m *SignMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignMessage.Unmarshal(m, b)
}
func (m *SignMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignMessage.Marshal(b, m, deterministic)
}
func (m *SignMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignMessage.Merge(m, src)
}
func (m *SignMessage) XXX_Size() int {
	return xxx_messageInfo_SignMessage.Size(m)
}
func (m *SignMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SignMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SignMessage proto.InternalMessageInfo

func (m *SignMessage) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *SignMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SignMessage) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type UpdateUspaceMessage struct {
	NodeID               int32    `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	FromNodeID           int32    `protobuf:"varint,2,opt,name=fromNodeID,proto3" json:"fromNodeID,omitempty"`
	Uspace               int64    `protobuf:"varint,3,opt,name=uspace,proto3" json:"uspace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUspaceMessage) Reset()         { *m = UpdateUspaceMessage{} }
func (m *UpdateUspaceMessage) String() string { return proto.CompactTextString(m) }
func (*UpdateUspaceMessage) ProtoMessage()    {}
func (*UpdateUspaceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{25}
}

func (m *UpdateUspaceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUspaceMessage.Unmarshal(m, b)
}
func (m *UpdateUspaceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUspaceMessage.Marshal(b, m, deterministic)
}
func (m *UpdateUspaceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUspaceMessage.Merge(m, src)
}
func (m *UpdateUspaceMessage) XXX_Size() int {
	return xxx_messageInfo_UpdateUspaceMessage.Size(m)
}
func (m *UpdateUspaceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUspaceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUspaceMessage proto.InternalMessageInfo

func (m *UpdateUspaceMessage) GetNodeID() int32 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *UpdateUspaceMessage) GetFromNodeID() int32 {
	if m != nil {
		return m.FromNodeID
	}
	return 0
}

func (m *UpdateUspaceMessage) GetUspace() int64 {
	if m != nil {
		return m.Uspace
	}
	return 0
}

type PunishMessage struct {
	NodeID               int32           `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Type                 int32           `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	NeedPunish           bool            `protobuf:"varint,3,opt,name=needPunish,proto3" json:"needPunish,omitempty"`
	Count                int32           `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Rule                 map[int32]int32 `protobuf:"bytes,5,rep,name=rule,proto3" json:"rule,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PunishMessage) Reset()         { *m = PunishMessage{} }
func (m *PunishMessage) String() string { return proto.CompactTextString(m) }
func (*PunishMessage) ProtoMessage()    {}
func (*PunishMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{26}
}

func (m *PunishMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PunishMessage.Unmarshal(m, b)
}
func (m *PunishMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PunishMessage.Marshal(b, m, deterministic)
}
func (m *PunishMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PunishMessage.Merge(m, src)
}
func (m *PunishMessage) XXX_Size() int {
	return xxx_messageInfo_PunishMessage.Size(m)
}
func (m *PunishMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PunishMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PunishMessage proto.InternalMessageInfo

func (m *PunishMessage) GetNodeID() int32 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *PunishMessage) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *PunishMessage) GetNeedPunish() bool {
	if m != nil {
		return m.NeedPunish
	}
	return false
}

func (m *PunishMessage) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PunishMessage) GetRule() map[int32]int32 {
	if m != nil {
		return m.Rule
	}
	return nil
}

type RebuiltMessage struct {
	NodeID               int32    `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RebuiltMessage) Reset()         { *m = RebuiltMessage{} }
func (m *RebuiltMessage) String() string { return proto.CompactTextString(m) }
func (*RebuiltMessage) ProtoMessage()    {}
func (*RebuiltMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{27}
}

func (m *RebuiltMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RebuiltMessage.Unmarshal(m, b)
}
func (m *RebuiltMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RebuiltMessage.Marshal(b, m, deterministic)
}
func (m *RebuiltMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RebuiltMessage.Merge(m, src)
}
func (m *RebuiltMessage) XXX_Size() int {
	return xxx_messageInfo_RebuiltMessage.Size(m)
}
func (m *RebuiltMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RebuiltMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RebuiltMessage proto.InternalMessageInfo

func (m *RebuiltMessage) GetNodeID() int32 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*StringMsg)(nil), "pb.StringMsg")
	proto.RegisterType((*String2Msg)(nil), "pb.String2Msg")
	proto.RegisterType((*Int32Msg)(nil), "pb.Int32Msg")
	proto.RegisterType((*Int64Msg)(nil), "pb.Int64Msg")
	proto.RegisterType((*NodeMsg)(nil), "pb.NodeMsg")
	proto.RegisterMapType((map[string]int64)(nil), "pb.NodeMsg.UspacesEntry")
	proto.RegisterType((*SuperNodeMsg)(nil), "pb.SuperNodeMsg")
	proto.RegisterType((*NodeStatMsg)(nil), "pb.NodeStatMsg")
	proto.RegisterType((*SpotCheckTaskMsg)(nil), "pb.SpotCheckTaskMsg")
	proto.RegisterType((*SpotCheckListMsg)(nil), "pb.SpotCheckListMsg")
	proto.RegisterType((*GetSpotCheckListResp)(nil), "pb.GetSpotCheckListResp")
	proto.RegisterType((*NodesResp)(nil), "pb.NodesResp")
	proto.RegisterType((*SuperNodesResp)(nil), "pb.SuperNodesResp")
	proto.RegisterType((*IncrUsedSpaceReq)(nil), "pb.IncrUsedSpaceReq")
	proto.RegisterType((*AllocNodesReq)(nil), "pb.AllocNodesReq")
	proto.RegisterType((*GetNodesReq)(nil), "pb.GetNodesReq")
	proto.RegisterType((*DNIReq)(nil), "pb.DNIReq")
	proto.RegisterType((*UpdateTaskStatusReq)(nil), "pb.UpdateTaskStatusReq")
	proto.RegisterType((*ShardCountMsg)(nil), "pb.ShardCountMsg")
	proto.RegisterType((*GetInvalidNodesResp)(nil), "pb.GetInvalidNodesResp")
	proto.RegisterType((*GetRebuildItemReq)(nil), "pb.GetRebuildItemReq")
	proto.RegisterType((*GetRebuildItemResp)(nil), "pb.GetRebuildItemResp")
	proto.RegisterType((*DownloadShardRequest)(nil), "pb.DownloadShardRequest")
	proto.RegisterType((*DownloadShardResponse)(nil), "pb.DownloadShardResponse")
	proto.RegisterType((*SignMessage)(nil), "pb.SignMessage")
	proto.RegisterType((*UpdateUspaceMessage)(nil), "pb.UpdateUspaceMessage")
	proto.RegisterType((*PunishMessage)(nil), "pb.PunishMessage")
	proto.RegisterMapType((map[int32]int32)(nil), "pb.PunishMessage.RuleEntry")
	proto.RegisterType((*RebuiltMessage)(nil), "pb.RebuiltMessage")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 1575 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xdd, 0x6e, 0xdb, 0xca,
	0x11, 0xb6, 0x64, 0xcb, 0x92, 0x46, 0x92, 0x7f, 0x36, 0x3e, 0x29, 0x8f, 0x4e, 0x9a, 0x38, 0x44,
	0x90, 0x0a, 0x69, 0xab, 0x38, 0x4a, 0x91, 0x14, 0x41, 0x6e, 0x6c, 0x2b, 0x75, 0xd4, 0xc6, 0x8a,
	0x41, 0xd9, 0x2d, 0x72, 0xd7, 0x95, 0xb8, 0x91, 0x08, 0xf3, 0xcf, 0xdc, 0xa5, 0x2d, 0xf5, 0xa2,
	0x77, 0x7d, 0x8e, 0x3e, 0x58, 0xd1, 0x77, 0x29, 0x66, 0x76, 0x29, 0x91, 0x72, 0x8a, 0xb4, 0xc0,
	0xb9, 0xdb, 0xf9, 0xf8, 0xed, 0xcc, 0xec, 0xfc, 0xed, 0x12, 0x1a, 0x6a, 0x11, 0x0b, 0xd9, 0x8d,
	0x93, 0x48, 0x45, 0xac, 0x1c, 0x8f, 0xed, 0x2a, 0x54, 0x3e, 0x04, 0xb1, 0x5a, 0xd8, 0x4f, 0xa1,
	0x3e, 0x52, 0x89, 0x17, 0x4e, 0xcf, 0xe5, 0x94, 0x1d, 0x40, 0xe5, 0x96, 0xfb, 0xa9, 0xb0, 0x4a,
	0x87, 0xa5, 0x4e, 0xdd, 0xd1, 0x82, 0xfd, 0x1e, 0x40, 0x53, 0x7a, 0xc8, 0x79, 0x08, 0xdb, 0x31,
	0x4f, 0x78, 0xf0, 0xca, 0x90, 0x8c, 0xb4, 0xc4, 0x7b, 0x56, 0x39, 0x87, 0xf7, 0xec, 0x43, 0xa8,
	0x0d, 0x42, 0xf5, 0xba, 0x77, 0x4f, 0x7f, 0x25, 0xd3, 0xaf, 0x19, 0x6f, 0x7e, 0x77, 0x8f, 0xb1,
	0x99, 0x31, 0xfe, 0x51, 0x85, 0xea, 0x30, 0x72, 0x05, 0x32, 0x76, 0xa0, 0xec, 0xf5, 0x8d, 0x82,
	0xb2, 0xd7, 0x47, 0xbb, 0x61, 0xe4, 0x8a, 0x41, 0x3f, 0xb3, 0xab, 0x25, 0xf2, 0x27, 0x1d, 0xff,
	0x49, 0x2c, 0xac, 0x4d, 0xe3, 0x0f, 0x49, 0x68, 0x21, 0xba, 0x0b, 0x45, 0x62, 0x6d, 0xe9, 0x33,
	0x92, 0xc0, 0x1e, 0x41, 0x3d, 0x4e, 0xa2, 0xaf, 0x9e, 0x3a, 0x9e, 0x4c, 0xac, 0x0a, 0x7d, 0x59,
	0x01, 0xa4, 0x2b, 0x8a, 0xfc, 0x41, 0xdf, 0xda, 0x36, 0xba, 0x48, 0xa2, 0x5d, 0x51, 0xe4, 0x7f,
	0x26, 0x7d, 0x55, 0xb3, 0x2b, 0x03, 0xd0, 0xd2, 0x4d, 0x1a, 0x29, 0x6e, 0xd5, 0xf4, 0x59, 0x48,
	0x40, 0x94, 0xbb, 0x6e, 0x22, 0xad, 0xfa, 0xe1, 0x26, 0xda, 0x27, 0x81, 0xed, 0xc1, 0xe6, 0xe4,
	0xe2, 0xca, 0x02, 0x3a, 0x16, 0x2e, 0xd1, 0x66, 0x20, 0x82, 0x28, 0x59, 0x58, 0x0d, 0x02, 0x8d,
	0x84, 0x36, 0xc7, 0x3c, 0x74, 0xef, 0x3c, 0x57, 0xcd, 0xac, 0x26, 0x7d, 0x5a, 0x01, 0xcc, 0x86,
	0x66, 0xc0, 0xe7, 0x7d, 0xae, 0xf8, 0x28, 0xe6, 0x13, 0x61, 0xb5, 0xc8, 0x74, 0x01, 0x63, 0xcf,
	0xa0, 0xc5, 0xa5, 0xf4, 0xa6, 0xa1, 0x70, 0x35, 0x69, 0x87, 0x48, 0x45, 0x90, 0x75, 0x60, 0x37,
	0x4e, 0x22, 0x37, 0x9d, 0x28, 0xef, 0x56, 0x68, 0xde, 0x2e, 0xf1, 0xd6, 0x61, 0xf4, 0x28, 0x95,
	0x99, 0xae, 0x3d, 0xe2, 0xac, 0x00, 0x3c, 0xc7, 0x9d, 0xf0, 0xa6, 0x33, 0x65, 0xed, 0x1f, 0x96,
	0x3a, 0x25, 0xc7, 0x48, 0x26, 0xd3, 0x9e, 0x6b, 0xb1, 0x65, 0x2d, 0x78, 0x2e, 0xa2, 0x89, 0xf0,
	0xf9, 0xc2, 0x7a, 0xa0, 0x51, 0x12, 0x50, 0x87, 0x54, 0x5c, 0xa5, 0xd2, 0x3a, 0xd0, 0xb1, 0xd0,
	0x12, 0x5a, 0x56, 0x5e, 0x20, 0xa4, 0xe2, 0x41, 0x6c, 0xfd, 0xa0, 0x2d, 0x2f, 0x01, 0x66, 0x41,
	0xf5, 0x56, 0x24, 0xd2, 0x8b, 0x42, 0xeb, 0x21, 0x6d, 0xcb, 0x44, 0xf6, 0x18, 0x20, 0x11, 0xe3,
	0xd4, 0xf3, 0x5d, 0x2f, 0x9c, 0x5a, 0xbf, 0xa0, 0x8f, 0x39, 0x04, 0xf5, 0x26, 0x82, 0xfb, 0xfa,
	0x44, 0x96, 0xd6, 0xbb, 0x04, 0xb0, 0x02, 0xd5, 0xdc, 0xfa, 0x91, 0xe0, 0xb2, 0x9a, 0xa3, 0x9c,
	0xcc, 0xad, 0xb6, 0x96, 0x93, 0x39, 0xe6, 0x52, 0xcc, 0x95, 0xf5, 0x13, 0xd5, 0x03, 0x2e, 0x59,
	0x0f, 0xaa, 0xa9, 0xc4, 0xbd, 0xd2, 0x7a, 0x74, 0xb8, 0xd9, 0x69, 0xf4, 0xac, 0x6e, 0x3c, 0xee,
	0x9a, 0x8a, 0xee, 0x5e, 0xe9, 0x4f, 0x1f, 0x42, 0x95, 0x2c, 0x9c, 0x8c, 0xa8, 0x33, 0x19, 0xa6,
	0xdc, 0xff, 0x8b, 0x8e, 0xde, 0x2f, 0xc9, 0xcb, 0x02, 0x86, 0xe7, 0x48, 0xc3, 0x44, 0x70, 0x97,
	0x8f, 0x7d, 0x61, 0x3d, 0x3e, 0x2c, 0x75, 0x6a, 0x4e, 0x0e, 0x61, 0x0c, 0xb6, 0x66, 0x5c, 0xce,
	0xac, 0x27, 0xe4, 0x0a, 0xad, 0xdb, 0xef, 0xa0, 0x99, 0x37, 0x88, 0xde, 0x5e, 0x8b, 0x85, 0x69,
	0x66, 0x5c, 0xae, 0x7a, 0xb0, 0x9c, 0xeb, 0xc1, 0x77, 0xe5, 0xdf, 0x97, 0xec, 0xbf, 0x43, 0x73,
	0x94, 0xc6, 0x22, 0xf9, 0xb9, 0x7a, 0xd1, 0x82, 0x6a, 0x9c, 0x78, 0xb7, 0xf8, 0x41, 0x77, 0x63,
	0x26, 0xae, 0xba, 0xa4, 0x92, 0xeb, 0x12, 0xfb, 0xdf, 0x25, 0x68, 0xa0, 0xed, 0x91, 0xe2, 0x0a,
	0xed, 0xdb, 0xd0, 0xe4, 0x54, 0x88, 0xe7, 0x5e, 0x28, 0x12, 0x69, 0x86, 0x46, 0x01, 0x63, 0x87,
	0xd0, 0x50, 0x91, 0xe2, 0xbe, 0xa1, 0xe8, 0x33, 0xe5, 0x21, 0xd6, 0x86, 0x5a, 0xc0, 0xe7, 0x97,
	0x88, 0x90, 0x7f, 0x9b, 0xce, 0x52, 0xce, 0xf7, 0x8a, 0x26, 0x6c, 0x15, 0x7b, 0x45, 0xb3, 0x0a,
	0xbd, 0xa2, 0x79, 0x95, 0xf5, 0x5e, 0xd1, 0x4c, 0xd3, 0x2b, 0x9a, 0xb3, 0xbd, 0xea, 0x15, 0x02,
	0xec, 0xbf, 0xc2, 0xde, 0x28, 0x8e, 0xd4, 0xe9, 0x4c, 0x4c, 0xae, 0x2f, 0xb9, 0xbc, 0xfe, 0x7f,
	0x62, 0xcc, 0x60, 0x0b, 0x83, 0x64, 0x22, 0x4c, 0x6b, 0xcc, 0xed, 0xed, 0x70, 0x60, 0x62, 0x8b,
	0x4b, 0xfb, 0x6f, 0x39, 0x0b, 0x9f, 0x3c, 0xa9, 0xcc, 0x44, 0x57, 0x5c, 0x5e, 0x0f, 0xfa, 0xd9,
	0x44, 0xd7, 0x12, 0x3b, 0x82, 0x1a, 0xae, 0x90, 0x66, 0x95, 0xa9, 0x6c, 0x0f, 0xb0, 0x6c, 0xd7,
	0x3d, 0x74, 0x96, 0xac, 0x62, 0x3f, 0x6e, 0xae, 0xf5, 0xa3, 0x7d, 0x09, 0x07, 0x67, 0x42, 0x15,
	0xcc, 0x3b, 0x42, 0xc6, 0xec, 0x3d, 0xec, 0xc8, 0x3c, 0x88, 0x79, 0xbc, 0x6f, 0xcd, 0x78, 0xeb,
	0xac, 0x71, 0xed, 0x2e, 0xd4, 0xb1, 0x24, 0x24, 0xa9, 0x7a, 0x0a, 0x15, 0x0c, 0x47, 0xa6, 0xa1,
	0x91, 0x6b, 0x33, 0x47, 0x7f, 0xb1, 0x4f, 0x60, 0x67, 0x59, 0xc3, 0x7a, 0xd3, 0x11, 0x80, 0x5c,
	0x22, 0x66, 0xe7, 0x1e, 0xd9, 0xce, 0xd5, 0xba, 0x93, 0xe3, 0xd8, 0x6f, 0x60, 0x6f, 0x10, 0x4e,
	0x92, 0xab, 0x6c, 0xc8, 0x39, 0xe2, 0x86, 0xf2, 0xe4, 0x2e, 0xf3, 0xe4, 0x62, 0x3e, 0xbc, 0x70,
	0x92, 0x98, 0x82, 0xa3, 0xb5, 0x7d, 0x06, 0xad, 0x63, 0xdf, 0x8f, 0x26, 0xc6, 0xf6, 0x0d, 0x36,
	0xb0, 0x9c, 0xf1, 0xc4, 0x3d, 0x8d, 0xd2, 0x50, 0x99, 0xcd, 0x39, 0x04, 0x53, 0x23, 0x92, 0x64,
	0xd0, 0x97, 0x94, 0x80, 0x8a, 0x63, 0x24, 0xfb, 0x57, 0xd0, 0x38, 0x13, 0x6a, 0xa9, 0xc6, 0x82,
	0xaa, 0xae, 0x02, 0xed, 0x7e, 0xc5, 0xc9, 0x44, 0xbb, 0x0b, 0xdb, 0xfd, 0xe1, 0xe0, 0x5b, 0xfe,
	0x1d, 0x40, 0x85, 0x0c, 0x91, 0x83, 0x4d, 0x47, 0x0b, 0xf6, 0x67, 0x78, 0x70, 0x15, 0xbb, 0x5c,
	0x09, 0x4c, 0xee, 0x88, 0xa6, 0x6c, 0x71, 0x73, 0x9d, 0x36, 0x77, 0x60, 0xd7, 0x0b, 0x69, 0x62,
	0xa3, 0x0f, 0xcb, 0x0a, 0xa9, 0x38, 0xeb, 0xb0, 0xfd, 0x0a, 0x5a, 0xa3, 0xe5, 0x79, 0xbe, 0x55,
	0xcf, 0x78, 0xf3, 0x85, 0xca, 0x84, 0x09, 0x97, 0xf6, 0x1f, 0xe1, 0xc1, 0x99, 0x50, 0x83, 0x95,
	0x22, 0x9d, 0xa6, 0xd7, 0xd0, 0x58, 0x45, 0x26, 0xcb, 0xd3, 0x3e, 0xe5, 0x29, 0x6f, 0xc0, 0xc9,
	0xb3, 0xec, 0x2f, 0xb0, 0x7f, 0x26, 0x94, 0xa3, 0x47, 0xfb, 0x40, 0x89, 0xc0, 0x84, 0x2b, 0xc0,
	0xd6, 0x1f, 0x64, 0x7e, 0x64, 0x22, 0x06, 0xc5, 0x0b, 0x5d, 0x31, 0xcf, 0x46, 0x1f, 0x09, 0x88,
	0xaa, 0xdc, 0x74, 0xd0, 0x82, 0x7d, 0x0e, 0x6c, 0x5d, 0xb5, 0x8c, 0xd9, 0x13, 0xd8, 0xc2, 0xd8,
	0x93, 0xe2, 0xb5, 0x02, 0xa4, 0x0f, 0x74, 0x97, 0xa1, 0x83, 0x3a, 0xa5, 0x4d, 0xc7, 0x48, 0x76,
	0x07, 0x0e, 0xfa, 0xd1, 0x5d, 0xe8, 0x47, 0xdc, 0xa5, 0xf3, 0x38, 0xe2, 0x26, 0x15, 0x52, 0x61,
	0x7c, 0xfe, 0xfc, 0xf1, 0x0f, 0xa4, 0xaf, 0xe9, 0xe0, 0xd2, 0xfe, 0x35, 0xfc, 0xb0, 0xc6, 0x94,
	0x71, 0x14, 0x4a, 0x1a, 0xf7, 0x2e, 0x57, 0xdc, 0x70, 0x69, 0x6d, 0x73, 0x68, 0x8c, 0xbc, 0x69,
	0x78, 0x2e, 0xa4, 0xe4, 0x53, 0x81, 0xd3, 0x90, 0x4f, 0x26, 0x18, 0x9b, 0x21, 0x0f, 0xb2, 0x77,
	0x5e, 0x1e, 0x5a, 0x2a, 0x29, 0xaf, 0x94, 0x60, 0x5f, 0xe3, 0xb8, 0xe3, 0x2a, 0x4d, 0x84, 0x19,
	0x30, 0x2b, 0xc0, 0x16, 0x59, 0xcd, 0xe8, 0x7b, 0x25, 0x33, 0xb5, 0x1a, 0x54, 0x3a, 0xc8, 0xd9,
	0xa0, 0x7a, 0x0c, 0xf0, 0x35, 0x89, 0x82, 0xe1, 0x6a, 0x88, 0x55, 0x9c, 0x1c, 0x82, 0xfb, 0xf4,
	0x1d, 0x68, 0xc2, 0x6d, 0x24, 0xfb, 0x5f, 0x25, 0x68, 0x5d, 0xa4, 0xa1, 0x27, 0x67, 0xdf, 0xb3,
	0xc0, 0x60, 0x0b, 0xdf, 0xbb, 0x46, 0x37, 0xad, 0xd1, 0x6a, 0x28, 0x84, 0xab, 0x15, 0x90, 0xe6,
	0x9a, 0x93, 0x43, 0x30, 0xc7, 0x14, 0x03, 0x1a, 0x96, 0x15, 0x47, 0x0b, 0xec, 0x25, 0x6c, 0x25,
	0xa9, 0x2f, 0xe8, 0x16, 0x6a, 0xf4, 0x7e, 0xc2, 0x6c, 0x16, 0x5c, 0xe8, 0x3a, 0xa9, 0x2f, 0xf4,
	0xc5, 0x4d, 0xc4, 0xf6, 0x5b, 0xa8, 0x2f, 0xa1, 0xfc, 0xd5, 0x5a, 0xf9, 0xc6, 0xd5, 0x5a, 0xc9,
	0x5f, 0xad, 0x1d, 0xd8, 0xd1, 0xa5, 0xa4, 0xbe, 0x73, 0xba, 0xde, 0x3f, 0xb7, 0xa1, 0xf6, 0xe5,
	0xb2, 0x3f, 0x3c, 0x9f, 0x06, 0x8a, 0x3d, 0x87, 0xfa, 0x48, 0xa8, 0x73, 0x2e, 0x95, 0x48, 0x58,
	0x13, 0xfd, 0xcb, 0x1e, 0xdb, 0xed, 0x3a, 0x4a, 0xfa, 0x91, 0xbf, 0xc1, 0x5e, 0x40, 0xf3, 0x74,
	0xc6, 0xc3, 0xa9, 0xf8, 0x10, 0xc9, 0x2b, 0xe7, 0x13, 0x6b, 0x51, 0xdf, 0x64, 0x0f, 0xff, 0x22,
	0xf7, 0x39, 0xd4, 0x87, 0xe2, 0xce, 0x64, 0x63, 0xf5, 0xa5, 0x5d, 0x50, 0x4f, 0xbc, 0xea, 0x29,
	0xf7, 0xfd, 0xe3, 0x8b, 0x01, 0xdb, 0x59, 0xa9, 0xbb, 0x6f, 0xbb, 0x0b, 0x7b, 0xba, 0x3e, 0xb2,
	0xab, 0x3b, 0x95, 0x2c, 0xdf, 0x18, 0xed, 0xbc, 0x60, 0x6f, 0xb0, 0x1e, 0xb4, 0x0a, 0xd3, 0x95,
	0x1d, 0x68, 0xc3, 0xc5, 0x81, 0x5b, 0xb4, 0x71, 0x04, 0xb0, 0x9a, 0xac, 0x8c, 0xa6, 0x42, 0x61,
	0xd2, 0xb6, 0x5b, 0x99, 0x0d, 0x1a, 0x26, 0xf6, 0x06, 0x7b, 0x06, 0xb5, 0xd1, 0x22, 0x24, 0x42,
	0xd1, 0x9b, 0x82, 0xde, 0xdf, 0x40, 0x2d, 0x1b, 0xb4, 0x6c, 0x17, 0x3f, 0xe4, 0xc6, 0xee, 0x7d,
	0x9d, 0x47, 0xd0, 0xc2, 0x1b, 0x6e, 0x79, 0x51, 0xe4, 0xa3, 0xc7, 0x0a, 0x37, 0x4a, 0xb6, 0xe3,
	0x2d, 0x3c, 0xcc, 0xef, 0xb8, 0x48, 0xbc, 0x5b, 0xae, 0x04, 0xbe, 0x80, 0x8a, 0xc9, 0x2c, 0xe6,
	0x8b, 0x82, 0xb4, 0x6f, 0x5c, 0x19, 0xf4, 0x4f, 0x16, 0x17, 0xfa, 0x3d, 0xb5, 0x96, 0xd5, 0xf5,
	0x84, 0xbd, 0x84, 0x5d, 0xb3, 0xe7, 0xbf, 0xed, 0x58, 0xcb, 0xc4, 0x9a, 0x77, 0xff, 0xbb, 0xa5,
	0xa7, 0xb0, 0x7d, 0xec, 0xba, 0xfd, 0xe1, 0x80, 0x01, 0x7e, 0xd1, 0x57, 0x50, 0x31, 0xb2, 0xbf,
	0x85, 0xdd, 0x63, 0x7a, 0x18, 0x51, 0x38, 0xe8, 0xf9, 0x90, 0x8b, 0xd6, 0xbd, 0xd0, 0xbe, 0xc0,
	0x9f, 0x50, 0xae, 0x3c, 0xa9, 0xbc, 0x49, 0x21, 0xae, 0xbb, 0x19, 0xd3, 0x3c, 0x0a, 0xed, 0x8d,
	0x93, 0x2e, 0xfc, 0xe8, 0x45, 0xdd, 0x45, 0xa4, 0x14, 0x9f, 0xcc, 0xb8, 0x17, 0x76, 0xb1, 0x73,
	0x82, 0x69, 0xa0, 0xba, 0xf1, 0xf8, 0xa4, 0x45, 0xc7, 0x9b, 0x06, 0xea, 0x02, 0x7f, 0x86, 0x3f,
	0x96, 0x2e, 0x4a, 0xe3, 0x6d, 0xfa, 0x2f, 0x7e, 0xfd, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc5,
	0x5f, 0xa8, 0x5e, 0x26, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// YTDNMgmtClient is the client API for YTDNMgmt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type YTDNMgmtClient interface {
	SetMaster(ctx context.Context, in *Int32Msg, opts ...grpc.CallOption) (*Empty, error)
	ChangeEosURL(ctx context.Context, in *StringMsg, opts ...grpc.CallOption) (*Empty, error)
	NewNodeID(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Int32Msg, error)
	CallAPI(ctx context.Context, in *String2Msg, opts ...grpc.CallOption) (*Empty, error)
	UpdateNodeStatus(ctx context.Context, in *NodeMsg, opts ...grpc.CallOption) (*NodeMsg, error)
	IncrUsedSpace(ctx context.Context, in *IncrUsedSpaceReq, opts ...grpc.CallOption) (*Empty, error)
	AllocNodes(ctx context.Context, in *AllocNodesReq, opts ...grpc.CallOption) (*NodesResp, error)
	SyncNode(ctx context.Context, in *NodeMsg, opts ...grpc.CallOption) (*Empty, error)
	GetNodes(ctx context.Context, in *GetNodesReq, opts ...grpc.CallOption) (*NodesResp, error)
	GetSuperNodes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SuperNodesResp, error)
	GetSuperNodePrivateKey(ctx context.Context, in *Int32Msg, opts ...grpc.CallOption) (*StringMsg, error)
	GetNodeIDByPubKey(ctx context.Context, in *StringMsg, opts ...grpc.CallOption) (*Int32Msg, error)
	GetNodeByPubKey(ctx context.Context, in *StringMsg, opts ...grpc.CallOption) (*NodeMsg, error)
	GetSuperNodeIDByPubKey(ctx context.Context, in *StringMsg, opts ...grpc.CallOption) (*Int32Msg, error)
	AddDNI(ctx context.Context, in *DNIReq, opts ...grpc.CallOption) (*Empty, error)
	ActiveNodesList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodesResp, error)
	Statistics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeStatMsg, error)
}

type yTDNMgmtClient struct {
	cc *grpc.ClientConn
}

func NewYTDNMgmtClient(cc *grpc.ClientConn) YTDNMgmtClient {
	return &yTDNMgmtClient{cc}
}

func (c *yTDNMgmtClient) SetMaster(ctx context.Context, in *Int32Msg, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.YTDNMgmt/SetMaster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yTDNMgmtClient) ChangeEosURL(ctx context.Context, in *StringMsg, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.YTDNMgmt/ChangeEosURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yTDNMgmtClient) NewNodeID(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Int32Msg, error) {
	out := new(Int32Msg)
	err := c.cc.Invoke(ctx, "/pb.YTDNMgmt/NewNodeID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yTDNMgmtClient) CallAPI(ctx context.Context, in *String2Msg, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.YTDNMgmt/CallAPI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yTDNMgmtClient) UpdateNodeStatus(ctx context.Context, in *NodeMsg, opts ...grpc.CallOption) (*NodeMsg, error) {
	out := new(NodeMsg)
	err := c.cc.Invoke(ctx, "/pb.YTDNMgmt/UpdateNodeStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yTDNMgmtClient) IncrUsedSpace(ctx context.Context, in *IncrUsedSpaceReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.YTDNMgmt/IncrUsedSpace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yTDNMgmtClient) AllocNodes(ctx context.Context, in *AllocNodesReq, opts ...grpc.CallOption) (*NodesResp, error) {
	out := new(NodesResp)
	err := c.cc.Invoke(ctx, "/pb.YTDNMgmt/AllocNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yTDNMgmtClient) SyncNode(ctx context.Context, in *NodeMsg, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.YTDNMgmt/SyncNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yTDNMgmtClient) GetNodes(ctx context.Context, in *GetNodesReq, opts ...grpc.CallOption) (*NodesResp, error) {
	out := new(NodesResp)
	err := c.cc.Invoke(ctx, "/pb.YTDNMgmt/GetNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yTDNMgmtClient) GetSuperNodes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SuperNodesResp, error) {
	out := new(SuperNodesResp)
	err := c.cc.Invoke(ctx, "/pb.YTDNMgmt/GetSuperNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yTDNMgmtClient) GetSuperNodePrivateKey(ctx context.Context, in *Int32Msg, opts ...grpc.CallOption) (*StringMsg, error) {
	out := new(StringMsg)
	err := c.cc.Invoke(ctx, "/pb.YTDNMgmt/GetSuperNodePrivateKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yTDNMgmtClient) GetNodeIDByPubKey(ctx context.Context, in *StringMsg, opts ...grpc.CallOption) (*Int32Msg, error) {
	out := new(Int32Msg)
	err := c.cc.Invoke(ctx, "/pb.YTDNMgmt/GetNodeIDByPubKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yTDNMgmtClient) GetNodeByPubKey(ctx context.Context, in *StringMsg, opts ...grpc.CallOption) (*NodeMsg, error) {
	out := new(NodeMsg)
	err := c.cc.Invoke(ctx, "/pb.YTDNMgmt/GetNodeByPubKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yTDNMgmtClient) GetSuperNodeIDByPubKey(ctx context.Context, in *StringMsg, opts ...grpc.CallOption) (*Int32Msg, error) {
	out := new(Int32Msg)
	err := c.cc.Invoke(ctx, "/pb.YTDNMgmt/GetSuperNodeIDByPubKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yTDNMgmtClient) AddDNI(ctx context.Context, in *DNIReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.YTDNMgmt/AddDNI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yTDNMgmtClient) ActiveNodesList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodesResp, error) {
	out := new(NodesResp)
	err := c.cc.Invoke(ctx, "/pb.YTDNMgmt/ActiveNodesList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yTDNMgmtClient) Statistics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeStatMsg, error) {
	out := new(NodeStatMsg)
	err := c.cc.Invoke(ctx, "/pb.YTDNMgmt/Statistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YTDNMgmtServer is the server API for YTDNMgmt service.
type YTDNMgmtServer interface {
	SetMaster(context.Context, *Int32Msg) (*Empty, error)
	ChangeEosURL(context.Context, *StringMsg) (*Empty, error)
	NewNodeID(context.Context, *Empty) (*Int32Msg, error)
	CallAPI(context.Context, *String2Msg) (*Empty, error)
	UpdateNodeStatus(context.Context, *NodeMsg) (*NodeMsg, error)
	IncrUsedSpace(context.Context, *IncrUsedSpaceReq) (*Empty, error)
	AllocNodes(context.Context, *AllocNodesReq) (*NodesResp, error)
	SyncNode(context.Context, *NodeMsg) (*Empty, error)
	GetNodes(context.Context, *GetNodesReq) (*NodesResp, error)
	GetSuperNodes(context.Context, *Empty) (*SuperNodesResp, error)
	GetSuperNodePrivateKey(context.Context, *Int32Msg) (*StringMsg, error)
	GetNodeIDByPubKey(context.Context, *StringMsg) (*Int32Msg, error)
	GetNodeByPubKey(context.Context, *StringMsg) (*NodeMsg, error)
	GetSuperNodeIDByPubKey(context.Context, *StringMsg) (*Int32Msg, error)
	AddDNI(context.Context, *DNIReq) (*Empty, error)
	ActiveNodesList(context.Context, *Empty) (*NodesResp, error)
	Statistics(context.Context, *Empty) (*NodeStatMsg, error)
}

// UnimplementedYTDNMgmtServer can be embedded to have forward compatible implementations.
type UnimplementedYTDNMgmtServer struct {
}

func (*UnimplementedYTDNMgmtServer) SetMaster(ctx context.Context, req *Int32Msg) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMaster not implemented")
}
func (*UnimplementedYTDNMgmtServer) ChangeEosURL(ctx context.Context, req *StringMsg) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeEosURL not implemented")
}
func (*UnimplementedYTDNMgmtServer) NewNodeID(ctx context.Context, req *Empty) (*Int32Msg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewNodeID not implemented")
}
func (*UnimplementedYTDNMgmtServer) CallAPI(ctx context.Context, req *String2Msg) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallAPI not implemented")
}
func (*UnimplementedYTDNMgmtServer) UpdateNodeStatus(ctx context.Context, req *NodeMsg) (*NodeMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNodeStatus not implemented")
}
func (*UnimplementedYTDNMgmtServer) IncrUsedSpace(ctx context.Context, req *IncrUsedSpaceReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncrUsedSpace not implemented")
}
func (*UnimplementedYTDNMgmtServer) AllocNodes(ctx context.Context, req *AllocNodesReq) (*NodesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocNodes not implemented")
}
func (*UnimplementedYTDNMgmtServer) SyncNode(ctx context.Context, req *NodeMsg) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncNode not implemented")
}
func (*UnimplementedYTDNMgmtServer) GetNodes(ctx context.Context, req *GetNodesReq) (*NodesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodes not implemented")
}
func (*UnimplementedYTDNMgmtServer) GetSuperNodes(ctx context.Context, req *Empty) (*SuperNodesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSuperNodes not implemented")
}
func (*UnimplementedYTDNMgmtServer) GetSuperNodePrivateKey(ctx context.Context, req *Int32Msg) (*StringMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSuperNodePrivateKey not implemented")
}
func (*UnimplementedYTDNMgmtServer) GetNodeIDByPubKey(ctx context.Context, req *StringMsg) (*Int32Msg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeIDByPubKey not implemented")
}
func (*UnimplementedYTDNMgmtServer) GetNodeByPubKey(ctx context.Context, req *StringMsg) (*NodeMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeByPubKey not implemented")
}
func (*UnimplementedYTDNMgmtServer) GetSuperNodeIDByPubKey(ctx context.Context, req *StringMsg) (*Int32Msg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSuperNodeIDByPubKey not implemented")
}
func (*UnimplementedYTDNMgmtServer) AddDNI(ctx context.Context, req *DNIReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDNI not implemented")
}
func (*UnimplementedYTDNMgmtServer) ActiveNodesList(ctx context.Context, req *Empty) (*NodesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActiveNodesList not implemented")
}
func (*UnimplementedYTDNMgmtServer) Statistics(ctx context.Context, req *Empty) (*NodeStatMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Statistics not implemented")
}

func RegisterYTDNMgmtServer(s *grpc.Server, srv YTDNMgmtServer) {
	s.RegisterService(&_YTDNMgmt_serviceDesc, srv)
}

func _YTDNMgmt_SetMaster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Int32Msg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTDNMgmtServer).SetMaster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.YTDNMgmt/SetMaster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTDNMgmtServer).SetMaster(ctx, req.(*Int32Msg))
	}
	return interceptor(ctx, in, info, handler)
}

func _YTDNMgmt_ChangeEosURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTDNMgmtServer).ChangeEosURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.YTDNMgmt/ChangeEosURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTDNMgmtServer).ChangeEosURL(ctx, req.(*StringMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _YTDNMgmt_NewNodeID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTDNMgmtServer).NewNodeID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.YTDNMgmt/NewNodeID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTDNMgmtServer).NewNodeID(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _YTDNMgmt_CallAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String2Msg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTDNMgmtServer).CallAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.YTDNMgmt/CallAPI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTDNMgmtServer).CallAPI(ctx, req.(*String2Msg))
	}
	return interceptor(ctx, in, info, handler)
}

func _YTDNMgmt_UpdateNodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTDNMgmtServer).UpdateNodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.YTDNMgmt/UpdateNodeStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTDNMgmtServer).UpdateNodeStatus(ctx, req.(*NodeMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _YTDNMgmt_IncrUsedSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrUsedSpaceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTDNMgmtServer).IncrUsedSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.YTDNMgmt/IncrUsedSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTDNMgmtServer).IncrUsedSpace(ctx, req.(*IncrUsedSpaceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _YTDNMgmt_AllocNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocNodesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTDNMgmtServer).AllocNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.YTDNMgmt/AllocNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTDNMgmtServer).AllocNodes(ctx, req.(*AllocNodesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _YTDNMgmt_SyncNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTDNMgmtServer).SyncNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.YTDNMgmt/SyncNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTDNMgmtServer).SyncNode(ctx, req.(*NodeMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _YTDNMgmt_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTDNMgmtServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.YTDNMgmt/GetNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTDNMgmtServer).GetNodes(ctx, req.(*GetNodesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _YTDNMgmt_GetSuperNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTDNMgmtServer).GetSuperNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.YTDNMgmt/GetSuperNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTDNMgmtServer).GetSuperNodes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _YTDNMgmt_GetSuperNodePrivateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Int32Msg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTDNMgmtServer).GetSuperNodePrivateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.YTDNMgmt/GetSuperNodePrivateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTDNMgmtServer).GetSuperNodePrivateKey(ctx, req.(*Int32Msg))
	}
	return interceptor(ctx, in, info, handler)
}

func _YTDNMgmt_GetNodeIDByPubKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTDNMgmtServer).GetNodeIDByPubKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.YTDNMgmt/GetNodeIDByPubKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTDNMgmtServer).GetNodeIDByPubKey(ctx, req.(*StringMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _YTDNMgmt_GetNodeByPubKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTDNMgmtServer).GetNodeByPubKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.YTDNMgmt/GetNodeByPubKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTDNMgmtServer).GetNodeByPubKey(ctx, req.(*StringMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _YTDNMgmt_GetSuperNodeIDByPubKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTDNMgmtServer).GetSuperNodeIDByPubKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.YTDNMgmt/GetSuperNodeIDByPubKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTDNMgmtServer).GetSuperNodeIDByPubKey(ctx, req.(*StringMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _YTDNMgmt_AddDNI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DNIReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTDNMgmtServer).AddDNI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.YTDNMgmt/AddDNI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTDNMgmtServer).AddDNI(ctx, req.(*DNIReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _YTDNMgmt_ActiveNodesList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTDNMgmtServer).ActiveNodesList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.YTDNMgmt/ActiveNodesList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTDNMgmtServer).ActiveNodesList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _YTDNMgmt_Statistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTDNMgmtServer).Statistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.YTDNMgmt/Statistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTDNMgmtServer).Statistics(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _YTDNMgmt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.YTDNMgmt",
	HandlerType: (*YTDNMgmtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetMaster",
			Handler:    _YTDNMgmt_SetMaster_Handler,
		},
		{
			MethodName: "ChangeEosURL",
			Handler:    _YTDNMgmt_ChangeEosURL_Handler,
		},
		{
			MethodName: "NewNodeID",
			Handler:    _YTDNMgmt_NewNodeID_Handler,
		},
		{
			MethodName: "CallAPI",
			Handler:    _YTDNMgmt_CallAPI_Handler,
		},
		{
			MethodName: "UpdateNodeStatus",
			Handler:    _YTDNMgmt_UpdateNodeStatus_Handler,
		},
		{
			MethodName: "IncrUsedSpace",
			Handler:    _YTDNMgmt_IncrUsedSpace_Handler,
		},
		{
			MethodName: "AllocNodes",
			Handler:    _YTDNMgmt_AllocNodes_Handler,
		},
		{
			MethodName: "SyncNode",
			Handler:    _YTDNMgmt_SyncNode_Handler,
		},
		{
			MethodName: "GetNodes",
			Handler:    _YTDNMgmt_GetNodes_Handler,
		},
		{
			MethodName: "GetSuperNodes",
			Handler:    _YTDNMgmt_GetSuperNodes_Handler,
		},
		{
			MethodName: "GetSuperNodePrivateKey",
			Handler:    _YTDNMgmt_GetSuperNodePrivateKey_Handler,
		},
		{
			MethodName: "GetNodeIDByPubKey",
			Handler:    _YTDNMgmt_GetNodeIDByPubKey_Handler,
		},
		{
			MethodName: "GetNodeByPubKey",
			Handler:    _YTDNMgmt_GetNodeByPubKey_Handler,
		},
		{
			MethodName: "GetSuperNodeIDByPubKey",
			Handler:    _YTDNMgmt_GetSuperNodeIDByPubKey_Handler,
		},
		{
			MethodName: "AddDNI",
			Handler:    _YTDNMgmt_AddDNI_Handler,
		},
		{
			MethodName: "ActiveNodesList",
			Handler:    _YTDNMgmt_ActiveNodesList_Handler,
		},
		{
			MethodName: "Statistics",
			Handler:    _YTDNMgmt_Statistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types.proto",
}
